name: fish_tank
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  flame: ^0.14.2
  shared_preferences: ^0.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  - assets/images/cheep-red.png
  - assets/images/cheep-green.png
  - assets/images/cheep-blue.png
  - assets/images/cheep-white.png
  - assets/images/cheep-red-right.png
  - assets/images/cheep-green-right.png
  - assets/images/cheep-blue-right.png
  - assets/images/cheep-white-right.png
  - assets/images/button-consume.png
  - assets/images/button-feed.png
  - assets/images/button-journey.png
  - assets/images/button-quick.png
  - assets/images/button-fight.png
  - assets/images/button-fight-2.png
  - assets/images/button-power.png
  - assets/images/button-item.png
  - assets/images/button-flee.png
  - assets/images/background-fish-tank-1.png
  - assets/images/background-fish-tank-2.png
  - assets/images/background-fish-tank-3.png
  - assets/images/background-fish-tank-4.png
  - assets/images/background-fish-tank-5.png
  - assets/images/bubble.png
  - assets/images/fish-sprite-1-L.png
  - assets/images/fish-sprite-1-R.png
  - assets/images/fish-sprite-1-Dead.png
  - assets/images/fish-sprite-2-L.png
  - assets/images/fish-sprite-2-R.png
  - assets/images/fish-sprite-2-L-200.png
  - assets/images/fish-sprite-2-500.png
  - assets/images/fish-sprite-3-L.png
  - assets/images/fish-sprite-3-R.png
  - assets/images/fish-sprite-3-500.png
  - assets/images/fish-sprite-4-L.png
  - assets/images/fish-sprite-4-R.png
  - assets/images/fish-sprite-4-500.png
  - assets/images/fish-sprite-5-L.png
  - assets/images/fish-sprite-5-R.png
  - assets/images/fish-sprite-5-500.png
  - assets/images/fish-food-1.png
  - assets/images/shop-exit-sign.png
  - assets/audio/sfx/bubblebobble11.wav
  - assets/audio/sfx/bubble-pop-1.wav
  - assets/audio/sfx/bubble-pop-2.wav



  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
